#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate Remaining League Team Files
Saudi, Egyptian, Turkish, Dutch, Portuguese, Belgian, Scottish, etc.
"""

import json
import os
from datetime import datetime

def save_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f"✓ {path} ({len(data['teams'])} teams)")

timestamp = datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")

# Saudi League (18 teams)
saudi_league_teams = [
    {"id": 2939, "name": "Al Nassr", "name_ar": "النصر", "code": "NAS", "logo": "https://media.api-sports.io/football/teams/2939.png", "founded": 1955, "stadium": {"name": "Mrsool Park", "name_ar": "مرسول بارك", "capacity": 25000, "city": "Riyadh", "city_ar": "الرياض"}, "nickname": "Al Alami", "nickname_ar": "العالمي", "colors": {"primary": "Yellow", "secondary": "Blue"}, "trophies": {"league_titles": 9, "domestic_cups": 6, "asian_cups": 0}},
    {"id": 2931, "name": "Al Hilal", "name_ar": "الهلال", "code": "HIL", "logo": "https://media.api-sports.io/football/teams/2931.png", "founded": 1957, "stadium": {"name": "King Fahd Stadium", "name_ar": "ملعب الملك فهد", "capacity": 67000, "city": "Riyadh", "city_ar": "الرياض"}, "nickname": "Al Zaeem", "nickname_ar": "الزعيم", "colors": {"primary": "Blue", "secondary": "White"}, "trophies": {"league_titles": 18, "domestic_cups": 10, "asian_cups": 4}},
    {"id": 2933, "name": "Al Ittihad", "name_ar": "الاتحاد", "code": "ITT", "logo": "https://media.api-sports.io/football/teams/2933.png", "founded": 1927, "stadium": {"name": "King Abdullah Sports City", "name_ar": "مدينة الملك عبدالله الرياضية", "capacity": 62000, "city": "Jeddah", "city_ar": "جدة"}, "nickname": "Al Ameed", "nickname_ar": "العميد", "colors": {"primary": "Black", "secondary": "Yellow"}, "trophies": {"league_titles": 9, "domestic_cups": 9, "asian_cups": 2}},
    {"id": 2932, "name": "Al Ahli", "name_ar": "الأهلي", "code": "AHL", "logo": "https://media.api-sports.io/football/teams/2932.png", "founded": 1937, "stadium": {"name": "King Abdullah Sports City", "name_ar": "مدينة الملك عبدالله الرياضية", "capacity": 62000, "city": "Jeddah", "city_ar": "جدة"}, "nickname": "Al Rayyan", "nickname_ar": "الريان", "colors": {"primary": "Green", "secondary": "White"}, "trophies": {"league_titles": 3, "domestic_cups": 13, "asian_cups": 0}},
    {"id": 2955, "name": "Al Shabab", "name_ar": "الشباب", "code": "SHA", "logo": "https://media.api-sports.io/football/teams/2955.png", "founded": 1947, "stadium": {"name": "Prince Faisal bin Fahd Stadium", "name_ar": "ملعب الأمير فيصل بن فهد", "capacity": 25000, "city": "Riyadh", "city_ar": "الرياض"}, "nickname": "Al Abyadh", "nickname_ar": "الأبيض", "colors": {"primary": "White", "secondary": "Blue"}, "trophies": {"league_titles": 6, "domestic_cups": 5, "asian_cups": 0}},
    {"id": 2938, "name": "Al Taawoun", "name_ar": "التعاون", "code": "TAA", "logo": "https://media.api-sports.io/football/teams/2938.png", "founded": 1956, "stadium": {"name": "King Abdullah Sport City Stadium", "name_ar": "ملعب مدينة الملك عبدالله الرياضية", "capacity": 15000, "city": "Buraidah", "city_ar": "بريدة"}, "nickname": "Al Asoud", "nickname_ar": "الأسود", "colors": {"primary": "Yellow", "secondary": "Black"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}},
    {"id": 2940, "name": "Al Fateh", "name_ar": "الفتح", "code": "FAT", "logo": "https://media.api-sports.io/football/teams/2940.png", "founded": 1958, "stadium": {"name": "Prince Abdullah bin Jalawi Stadium", "name_ar": "ملعب الأمير عبدالله بن جلوي", "capacity": 22000, "city": "Al-Hasa", "city_ar": "الأحساء"}, "nickname": "Al Romansi", "nickname_ar": "الرومانسي", "colors": {"primary": "Orange", "secondary": "Black"}, "trophies": {"league_titles": 0, "domestic_cups": 2, "asian_cups": 0}},
    {"id": 2944, "name": "Al Khaleej", "name_ar": "الخليج", "code": "KHA", "logo": "https://media.api-sports.io/football/teams/2944.png", "founded": 1945, "stadium": {"name": "Prince Mohamed bin Fahd Stadium", "name_ar": "ملعب الأمير محمد بن فهد", "capacity": 35000, "city": "Dammam", "city_ar": "الدمام"}, "nickname": "Al Omrani", "nickname_ar": "العمراني", "colors": {"primary": "Blue", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 1, "asian_cups": 0}},
    {"id": 2947, "name": "Al Ettifaq", "name_ar": "الاتفاق", "code": "ETT", "logo": "https://media.api-sports.io/football/teams/2947.png", "founded": 1945, "stadium": {"name": "Prince Mohamed bin Fahd Stadium", "name_ar": "ملعب الأمير محمد بن فهد", "capacity": 35000, "city": "Dammam", "city_ar": "الدمام"}, "nickname": "Al Thalab", "nickname_ar": "الثعلب", "colors": {"primary": "Yellow", "secondary": "Black"}, "trophies": {"league_titles": 1, "domestic_cups": 2, "asian_cups": 0}},
    {"id": 2952, "name": "Damac", "name_ar": "ضمك", "code": "DAM", "logo": "https://media.api-sports.io/football/teams/2952.png", "founded": 1972, "stadium": {"name": "Prince Sultan bin Abdulaziz Stadium", "name_ar": "ملعب الأمير سلطان بن عبدالعزيز", "capacity": 7000, "city": "Abha", "city_ar": "أبها"}, "nickname": "Al Nour", "nickname_ar": "النور", "colors": {"primary": "Blue", "secondary": "Yellow"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}},
    {"id": 2937, "name": "Al Feiha", "name_ar": "الفيحاء", "code": "FEI", "logo": "https://media.api-sports.io/football/teams/2937.png", "founded": 1954, "stadium": {"name": "Al Majma'ah Sports City Stadium", "name_ar": "ملعب مدينة المجمعة الرياضية", "capacity": 6500, "city": "Al Majma'ah", "city_ar": "المجمعة"}, "nickname": "Al Anwar", "nickname_ar": "الأنوار", "colors": {"primary": "Orange", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}},
    {"id": 2950, "name": "Al Raed", "name_ar": "الرائد", "code": "RAE", "logo": "https://media.api-sports.io/football/teams/2950.png", "founded": 1954, "stadium": {"name": "King Abdullah Sport City Stadium", "name_ar": "ملعب مدينة الملك عبدالله الرياضية", "capacity": 15000, "city": "Buraidah", "city_ar": "بريدة"}, "nickname": "Al Akhdar", "nickname_ar": "الأخضر", "colors": {"primary": "Green", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}},
    {"id": 2946, "name": "Al Wehda", "name_ar": "الوحدة", "code": "WEH", "logo": "https://media.api-sports.io/football/teams/2946.png", "founded": 1945, "stadium": {"name": "King Abdulaziz Stadium", "name_ar": "ملعب الملك عبدالعزيز", "capacity": 24000, "city": "Mecca", "city_ar": "مكة"}, "nickname": "Al Amamah", "nickname_ar": "العمامة", "colors": {"primary": "Orange", "secondary": "Black"}, "trophies": {"league_titles": 0, "domestic_cups": 1, "asian_cups": 0}},
    {"id": 15489, "name": "Abha", "name_ar": "أبها", "code": "ABH", "logo": "https://media.api-sports.io/football/teams/15489.png", "founded": 2003, "stadium": {"name": "Prince Sultan bin Abdulaziz Stadium", "name_ar": "ملعب الأمير سلطان بن عبدالعزيز", "capacity": 7000, "city": "Abha", "city_ar": "أبها"}, "nickname": "Al Najoom", "nickname_ar": "النجوم", "colors": {"primary": "Green", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}},
    {"id": 14484, "name": "Al Riyadh", "name_ar": "الرياض", "code": "RIY", "logo": "https://media.api-sports.io/football/teams/14484.png", "founded": 1953, "stadium": {"name": "Prince Turki bin Abdulaziz Stadium", "name_ar": "ملعب الأمير تركي بن عبدالعزيز", "capacity": 10000, "city": "Riyadh", "city_ar": "الرياض"}, "nickname": "Al Farhani", "nickname_ar": "الفرحاني", "colors": {"primary": "Red", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}},
    {"id": 2935, "name": "Al Tai", "name_ar": "التعاون", "code": "TAI", "logo": "https://media.api-sports.io/football/teams/2935.png", "founded": 1956, "stadium": {"name": "Hail City Stadium", "name_ar": "ملعب مدينة حائل", "capacity": 12000, "city": "Hail", "city_ar": "حائل"}, "nickname": "Al Jabalain", "nickname_ar": "الجبلين", "colors": {"primary": "Blue", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}},
    {"id": 2953, "name": "Al Hazem", "name_ar": "الحزم", "code": "HAZ", "logo": "https://media.api-sports.io/football/teams/2953.png", "founded": 1956, "stadium": {"name": "Prince Saud bin Jalawi Stadium", "name_ar": "ملعب الأمير سعود بن جلوي", "capacity": 7000, "city": "Al-Rass", "city_ar": "الرس"}, "nickname": "Al Sakaliba", "nickname_ar": "الصقالبة", "colors": {"primary": "Blue", "secondary": "Red"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}},
    {"id": 2948, "name": "Al Okhdood", "name_ar": "العقد", "code": "OKH", "logo": "https://media.api-sports.io/football/teams/2948.png", "founded": 1984, "stadium": {"name": "Prince Faisal bin Fahd Stadium", "name_ar": "ملعب الأمير فيصل بن فهد", "capacity": 5000, "city": "Najran", "city_ar": "نجران"}, "nickname": "Al Janoubieen", "nickname_ar": "الجنوبيين", "colors": {"primary": "Orange", "secondary": "Black"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "asian_cups": 0}}
]

saudi_league = {
    "league": {"id": 307, "name": "Saudi Professional League", "name_ar": "دوري روشن السعودي", "country": "Saudi Arabia", "country_ar": "السعودية", "logo": "https://media.api-sports.io/football/leagues/307.png", "season": "2024-2025"},
    "teams": saudi_league_teams,
    "total_teams": len(saudi_league_teams),
    "last_updated": timestamp
}

save_json('data/teams/saudi_league.json', saudi_league)

# Egyptian League (18 teams)
egyptian_league_teams = [
    {"id": 1029, "name": "Al Ahly", "name_ar": "الأهلي", "code": "AHL", "logo": "https://media.api-sports.io/football/teams/1029.png", "founded": 1907, "stadium": {"name": "Al Ahly WE Al Salam Stadium", "name_ar": "ملعب الأهلي وي السلام", "capacity": 30000, "city": "Cairo", "city_ar": "القاهرة"}, "nickname": "The Red Castle", "nickname_ar": "القلعة الحمراء", "colors": {"primary": "Red", "secondary": "White"}, "trophies": {"league_titles": 43, "domestic_cups": 39, "african_cups": 11}},
    {"id": 1030, "name": "Zamalek", "name_ar": "الزمالك", "code": "ZAM", "logo": "https://media.api-sports.io/football/teams/1030.png", "founded": 1911, "stadium": {"name": "Cairo International Stadium", "name_ar": "استاد القاهرة الدولي", "capacity": 75000, "city": "Cairo", "city_ar": "القاهرة"}, "nickname": "The White Knights", "nickname_ar": "الفرسان البيض", "colors": {"primary": "White", "secondary": "Red"}, "trophies": {"league_titles": 14, "domestic_cups": 28, "african_cups": 5}},
    {"id": 1033, "name": "Pyramids FC", "name_ar": "بيراميدز", "code": "PYR", "logo": "https://media.api-sports.io/football/teams/1033.png", "founded": 2008, "stadium": {"name": "30 June Stadium", "name_ar": "استاد 30 يونيو", "capacity": 30000, "city": "Cairo", "city_ar": "القاهرة"}, "nickname": "The Pharaohs", "nickname_ar": "الفراعنة", "colors": {"primary": "Blue", "secondary": "Yellow"}, "trophies": {"league_titles": 0, "domestic_cups": 1, "african_cups": 0}},
    {"id": 1046, "name": "Al Masry", "name_ar": "المصري", "code": "MAS", "logo": "https://media.api-sports.io/football/teams/1046.png", "founded": 1920, "stadium": {"name": "Port Said Stadium", "name_ar": "استاد بورسعيد", "capacity": 25000, "city": "Port Said", "city_ar": "بورسعيد"}, "nickname": "The Green Eagles", "nickname_ar": "النسور الخضراء", "colors": {"primary": "Green", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 2, "african_cups": 0}},
    {"id": 1032, "name": "Ismaily", "name_ar": "الإسماعيلي", "code": "ISM", "logo": "https://media.api-sports.io/football/teams/1032.png", "founded": 1921, "stadium": {"name": "Ismailia Stadium", "name_ar": "استاد الإسماعيلية", "capacity": 18525, "city": "Ismailia", "city_ar": "الإسماعيلية"}, "nickname": "The Dervishes", "nickname_ar": "الدراويش", "colors": {"primary": "Yellow", "secondary": "Black"}, "trophies": {"league_titles": 3, "domestic_cups": 2, "african_cups": 0}},
    {"id": 1044, "name": "Al Ittihad Alexandria", "name_ar": "الاتحاد السكندري", "code": "ITT", "logo": "https://media.api-sports.io/football/teams/1044.png", "founded": 1914, "stadium": {"name": "Alexandria Stadium", "name_ar": "استاد الإسكندرية", "capacity": 20000, "city": "Alexandria", "city_ar": "الإسكندرية"}, "nickname": "The Railwaymen", "nickname_ar": "السكة الحديد", "colors": {"primary": "Blue", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 2, "african_cups": 0}},
    {"id": 1045, "name": "Ceramica Cleopatra", "name_ar": "سيراميكا كليوباترا", "code": "CER", "logo": "https://media.api-sports.io/football/teams/1045.png", "founded": 2006, "stadium": {"name": "Suez Stadium", "name_ar": "استاد السويس", "capacity": 25000, "city": "Suez", "city_ar": "السويس"}, "nickname": "The Potters", "nickname_ar": "الفخاريين", "colors": {"primary": "Yellow", "secondary": "Blue"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1051, "name": "Smouha", "name_ar": "سموحة", "code": "SMO", "logo": "https://media.api-sports.io/football/teams/1051.png", "founded": 1949, "stadium": {"name": "Alexandria Stadium", "name_ar": "استاد الإسكندرية", "capacity": 20000, "city": "Alexandria", "city_ar": "الإسكندرية"}, "nickname": "The Sky Blues", "nickname_ar": "السماوي", "colors": {"primary": "Sky Blue", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1047, "name": "ZED FC", "name_ar": "زيد", "code": "ZED", "logo": "https://media.api-sports.io/football/teams/1047.png", "founded": 2020, "stadium": {"name": "Gehaz El Reyada Stadium", "name_ar": "استاد جهاز الرياضة", "capacity": 5000, "city": "6th of October City", "city_ar": "مدينة 6 أكتوبر"}, "nickname": "The Warriors", "nickname_ar": "المحاربون", "colors": {"primary": "Red", "secondary": "Black"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1048, "name": "Future FC", "name_ar": "فيوتشر", "code": "FUT", "logo": "https://media.api-sports.io/football/teams/1048.png", "founded": 2015, "stadium": {"name": "Al Salam Stadium", "name_ar": "استاد السلام", "capacity": 30000, "city": "Cairo", "city_ar": "القاهرة"}, "nickname": "The Future", "nickname_ar": "المستقبل", "colors": {"primary": "Blue", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1049, "name": "Pharco FC", "name_ar": "فاركو", "code": "PHA", "logo": "https://media.api-sports.io/football/teams/1049.png", "founded": 2009, "stadium": {"name": "Suez Stadium", "name_ar": "استاد السويس", "capacity": 25000, "city": "Suez", "city_ar": "السويس"}, "nickname": "The Pharaohs", "nickname_ar": "الفراعنة", "colors": {"primary": "Red", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1050, "name": "National Bank", "name_ar": "البنك الأهلي", "code": "NBE", "logo": "https://media.api-sports.io/football/teams/1050.png", "founded": 1980, "stadium": {"name": "Cairo International Stadium", "name_ar": "استاد القاهرة الدولي", "capacity": 75000, "city": "Cairo", "city_ar": "القاهرة"}, "nickname": "The Bankers", "nickname_ar": "البنكيون", "colors": {"primary": "Red", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1052, "name": "El Gouna", "name_ar": "الجونة", "code": "GOU", "logo": "https://media.api-sports.io/football/teams/1052.png", "founded": 2003, "stadium": {"name": "El Gouna Stadium", "name_ar": "استاد الجونة", "capacity": 10000, "city": "El Gouna", "city_ar": "الجونة"}, "nickname": "The Red Sea Team", "nickname_ar": "فريق البحر الأحمر", "colors": {"primary": "Red", "secondary": "Black"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1053, "name": "El Dakhl", "name_ar": "الداخلية", "code": "DAK", "logo": "https://media.api-sports.io/football/teams/1053.png", "founded": 1989, "stadium": {"name": "Military Academy Stadium", "name_ar": "استاد الكلية الحربية", "capacity": 22000, "city": "Cairo", "city_ar": "القاهرة"}, "nickname": "The Interior", "nickname_ar": "الداخلية", "colors": {"primary": "Blue", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1054, "name": "Ghazl El Mahalla", "name_ar": "غزل المحلة", "code": "GHZ", "logo": "https://media.api-sports.io/football/teams/1054.png", "founded": 1936, "stadium": {"name": "Ghazl El Mahalla Stadium", "name_ar": "استاد غزل المحلة", "capacity": 20000, "city": "El Mahalla El Kubra", "city_ar": "المحلة الكبرى"}, "nickname": "The Spinners", "nickname_ar": "النساجون", "colors": {"primary": "Yellow", "secondary": "Red"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1055, "name": "Enppi", "name_ar": "إنبي", "code": "ENP", "logo": "https://media.api-sports.io/football/teams/1055.png", "founded": 1980, "stadium": {"name": "Petrosport Stadium", "name_ar": "استاد بتروسبورت", "capacity": 25000, "city": "Cairo", "city_ar": "القاهرة"}, "nickname": "The Petroleum", "nickname_ar": "البترول", "colors": {"primary": "Yellow", "secondary": "Black"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}},
    {"id": 1056, "name": "Al Mokawloon", "name_ar": "المقاولون العرب", "code": "MOK", "logo": "https://media.api-sports.io/football/teams/1056.png", "founded": 1973, "stadium": {"name": "Osman Ahmed Osman Stadium", "name_ar": "استاد عثمان أحمد عثمان", "capacity": 35000, "city": "Cairo", "city_ar": "القاهرة"}, "nickname": "The Contractors", "nickname_ar": "المقاولون", "colors": {"primary": "Orange", "secondary": "Black"}, "trophies": {"league_titles": 0, "domestic_cups": 1, "african_cups": 0}},
    {"id": 1057, "name": "Baladiyat El Mahalla", "name_ar": "بلدية المحلة", "code": "BAL", "logo": "https://media.api-sports.io/football/teams/1057.png", "founded": 2006, "stadium": {"name": "Ghazl El Mahalla Stadium", "name_ar": "استاد غزل المحلة", "capacity": 20000, "city": "El Mahalla El Kubra", "city_ar": "المحلة الكبرى"}, "nickname": "The Municipality", "nickname_ar": "البلدية", "colors": {"primary": "Blue", "secondary": "White"}, "trophies": {"league_titles": 0, "domestic_cups": 0, "african_cups": 0}}
]

egyptian_league = {
    "league": {"id": 233, "name": "Premier League", "name_ar": "الدوري المصري الممتاز", "country": "Egypt", "country_ar": "مصر", "logo": "https://media.api-sports.io/football/leagues/233.png", "season": "2024-2025"},
    "teams": egyptian_league_teams,
    "total_teams": len(egyptian_league_teams),
    "last_updated": timestamp
}

save_json('data/teams/egyptian_league.json', egyptian_league)

print(f"\n✅ Created Saudi and Egyptian leagues ({len(saudi_league_teams) + len(egyptian_league_teams)} teams)")
